# Echocardiogram_Report_Extraction_Config.yaml

report_information:
  report_id: "string"                    # 报告唯一标识
  patient_id: "string"                   # 患者唯一标识
  exam_date: "YYYY-MM-DD"                # 检查日期，格式：YYYY-MM-DD
  exam_location: "string"                # 检查部位，如“超声心动图”
  conclusion: "string"                   # 结论
  recommendations: "string"              # 建议（如适用）

patient_basic_information:
  name: "string"                         # 姓名
  gender: "string"                       # 性别
  age: "integer"                         # 年龄
  birth_date: "YYYY-MM-DD"               # 出生日期，格式：YYYY-MM-DD
  height_cm: "float"                     # 身高，单位：厘米
  weight_kg: "float"                     # 体重，单位：公斤
  medical_record_number: "string"        # 病历号
  contact_information: "string"          # 联系方式
  allergy_history: "string"              # 过敏史
  family_history: "string"               # 家族病史
  past_medical_history: "string"         # 既往病史
  smoking_history: "string"              # 吸烟史
  occupational_exposure_history: "string" # 职业暴露史

echocardiogram_findings:
  chambers:
    left_atrium:
      size_cm: "float"                    # 左心房大小，单位：厘米
      size_unit: "string"                 # 单位，通常为“cm”
      volume_ml: "float"                   # 左心房容积，单位：毫升
      volume_unit: "string"                # 单位，通常为“ml”
      wall_thickness_mm: "float"           # 左心房壁厚，单位：毫米
      wall_thickness_unit: "string"        # 单位，通常为“mm”
      function: "string"                   # 功能描述，如“正常”、“扩大”等

    left_ventricle:
      size_cm: "float"                    # 左心室大小，单位：厘米
      size_unit: "string"                 # 单位，通常为“cm”
      volume_ml: "float"                   # 左心室容积，单位：毫升
      volume_unit: "string"                # 单位，通常为“ml”
      wall_thickness_mm: "float"           # 左心室壁厚，单位：毫米
      wall_thickness_unit: "string"        # 单位，通常为“mm”
      ejection_fraction_percent: "float"    # 射血分数，单位：%
      fractional_shortening_percent: "float" # 短缩分数，单位：%
      function: "string"                   # 功能描述，如“正常”、“收缩功能减退”等

    right_atrium:
      size_cm: "float"                    # 右心房大小，单位：厘米
      size_unit: "string"                 # 单位，通常为“cm”
      volume_ml: "float"                   # 右心房容积，单位：毫升
      volume_unit: "string"                # 单位，通常为“ml”
      wall_thickness_mm: "float"           # 右心房壁厚，单位：毫米
      wall_thickness_unit: "string"        # 单位，通常为“mm”
      function: "string"                   # 功能描述，如“正常”、“扩大”等

    right_ventricle:
      size_cm: "float"                    # 右心室大小，单位：厘米
      size_unit: "string"                 # 单位，通常为“cm”
      volume_ml: "float"                   # 右心室容积，单位：毫升
      volume_unit: "string"                # 单位，通常为“ml”
      wall_thickness_mm: "float"           # 右心室壁厚，单位：毫米
      wall_thickness_unit: "string"        # 单位，通常为“mm”
      function: "string"                   # 功能描述，如“正常”、“收缩功能减退”等

  valves:
    mitral_valve:
      morphology: "string"                  # 形态，如“正常”、“瓣膜增厚”等
      regurgitation_grade: "integer"        # 返流分级，如1-4级
      stenosis_grade: "integer"             # 狭窄分级，如1-4级
      associated_features: "string"         # 相关特征，如“钙化”、“脱垂”等

    aortic_valve:
      morphology: "string"                  # 形态，如“正常”、“瓣膜增厚”等
      regurgitation_grade: "integer"        # 返流分级，如1-4级
      stenosis_grade: "integer"             # 狭窄分级，如1-4级
      associated_features: "string"         # 相关特征，如“钙化”、“脱垂”等

    tricuspid_valve:
      morphology: "string"                  # 形态，如“正常”、“瓣膜增厚”等
      regurgitation_grade: "integer"        # 返流分级，如1-4级
      stenosis_grade: "integer"             # 狭窄分级，如1-4级
      associated_features: "string"         # 相关特征，如“钙化”、“脱垂”等

    pulmonary_valve:
      morphology: "string"                  # 形态，如“正常”、“瓣膜增厚”等
      regurgitation_grade: "integer"        # 返流分级，如1-4级
      stenosis_grade: "integer"             # 狭窄分级，如1-4级
      associated_features: "string"         # 相关特征，如“钙化”、“脱垂”等

  pericardium:
    effusion_present: "boolean"             # 是否存在心包积液
    effusion_volume_ml: "float"             # 心包积液量，单位：毫升
    effusion_characteristics: "string"      # 心包积液特征，如“无”、“少量”、“中量”、“大量”
    constrictive_pericarditis: "boolean"    # 是否存在限制性心包炎

  wall_motion:
    abnormalities_present: "boolean"        # 是否存在壁运动异常
    regions_with_abnormal_motion: "list"    # 存在壁运动异常的区域，如“前壁”、“侧壁”等
    description: "string"                   # 描述，如“运动减弱”、“运动缺失”等

  doppler_findings:
    mitral_inflow:
      e_velocity_cm_s: "float"              # E波速度，单位：cm/s
      a_velocity_cm_s: "float"              # A波速度，单位：cm/s
      e_a_ratio: "float"                     # E/A比值
      deceleration_time_ms: "float"          # E波减速时间，单位：毫秒

    tricuspid_inflow:
      e_velocity_cm_s: "float"              # E波速度，单位：cm/s
      a_velocity_cm_s: "float"              # A波速度，单位：cm/s
      e_a_ratio: "float"                     # E/A比值
      deceleration_time_ms: "float"          # E波减速时间，单位：毫秒

    aortic_outflow:
      velocity_cm_s: "float"                # 最高速度，单位：cm/s
      pressure_gradient_mmHg: "float"        # 压力梯度，单位：mmHg

    pulmonic_outflow:
      velocity_cm_s: "float"                # 最高速度，单位：cm/s
      pressure_gradient_mmHg: "float"        # 压力梯度，单位：mmHg

quantitative_metrics:
  ejection_fraction_percent: "float"          # 射血分数，单位：%
  fractional_shortening_percent: "float"      # 短缩分数，单位：%
  left_atrium_volume_ml: "float"               # 左心房容积，单位：毫升
  left_ventricle_volume_ml: "float"            # 左心室容积，单位：毫升
  right_atrium_volume_ml: "float"              # 右心房容积，单位：毫升
  right_ventricle_volume_ml: "float"           # 右心室容积，单位：毫升
  mitral_valve_area_cm2: "float"               # 二尖瓣面积，单位：cm²
  aortic_valve_area_cm2: "float"               # 主动脉瓣面积，单位：cm²
  tricuspid_valve_area_cm2: "float"            # 三尖瓣面积，单位：cm²
  pulmonary_valve_area_cm2: "float"            # 肺动脉瓣面积，单位：cm²

diagnostic_opinion:
  accurate_diagnosis: "string"                  # 准确的诊断名称

comparative_study:
  compared_with_past_ecg: "string"              # 与既往心电图对比描述
  change_description: "string"                  # 变化描述，如“增大”、“缩小”等

report_details:
  report_generated_date: "YYYY-MM-DD"           # 报告生成日期
  report_generated_time: "HH:MM"                # 报告生成时间
  cardiologist_name: "string"                   # 心脏病专科医生姓名
  cardiologist_signature: "string"              # 心脏病专科医生签名
  report_number: "string"                       # 报告编号
  remarks: "string"                             # 备注

attachments_and_additional_info:
  image_links:                                  # 影像图像链接列表
    - "string"                                  # 例如："http://example.com/ecg_image1"
    - "string"                                  # 例如："http://example.com/ecg_image2"
  external_reports:                             # 外部相关报告链接列表（如适用）
    - "string"                                  # 例如："http://exam
