# Holter_ECG_Report_Extraction_Config.yaml

report_information:
  report_id: "string"                  # 报告唯一标识
  patient_id: "string"                 # 患者唯一标识
  exam_start_date: "YYYY-MM-DD"        # 检查开始日期，格式：YYYY-MM-DD
  exam_start_time: "HH:MM"             # 检查开始时间，格式：HH:MM
  exam_end_date: "YYYY-MM-DD"          # 检查结束日期，格式：YYYY-MM-DD
  exam_end_time: "HH:MM"               # 检查结束时间，格式：HH:MM
  exam_location: "string"              # 检查部位，如“动态心电图”
  conclusion: "string"                 # 结论
  recommendations: "string"            # 建议（如适用）

patient_basic_information:
  name: "string"                       # 姓名
  gender: "string"                     # 性别
  age: "integer"                       # 年龄
  birth_date: "YYYY-MM-DD"             # 出生日期，格式：YYYY-MM-DD
  height_cm: "float"                   # 身高，单位：厘米
  weight_kg: "float"                   # 体重，单位：公斤
  medical_record_number: "string"      # 病历号
  contact_information: "string"        # 联系方式
  allergy_history: "string"            # 过敏史
  family_history: "string"             # 家族病史
  past_medical_history: "string"       # 既往病史
  smoking_history: "string"            # 吸烟史
  occupational_exposure_history: "string" # 职业暴露史

ECG_findings:
  average_heart_rate_bpm: "integer"     # 平均心率，单位：次/分钟
  minimum_heart_rate_bpm: "integer"     # 最低心率，单位：次/分钟
  maximum_heart_rate_bpm: "integer"     # 最高心率，单位：次/分钟
  heart_rate_variability: "string"       # 心率变异性，如“正常”、“降低”、“增加”
  rhythm: "string"                       # 心律，如“窦性心律”、“房颤”、“室性早搏”等
  episodes_of_arrhythmia:               # 心律失常发作
    - episode_id: "string"               # 发作唯一标识
      type: "string"                      # 发作类型，如“房性早搏”、“室性早搏”、“房颤”等
      start_time: "HH:MM"                 # 发作开始时间，格式：HH:MM
      end_time: "HH:MM"                   # 发作结束时间，格式：HH:MM
      duration_seconds: "integer"         # 发作持续时间，单位：秒
      heart_rate_bpm: "integer"            # 发作期间心率，单位：次/分钟
      associated_features: "string"       # 相关特征，如“心悸”、“胸痛”等

quantitative_metrics:
  total_monitoring_duration_hours: "float"  # 总监测时长，单位：小时
  total_episodes_of_arrhythmia: "integer"   # 心律失常发作总数
  average_heart_rate_bpm: "integer"          # 平均心率，单位：次/分钟
  minimum_heart_rate_bpm: "integer"          # 最低心率，单位：次/分钟
  maximum_heart_rate_bpm: "integer"          # 最高心率，单位：次/分钟
  heart_rate_variability_index: "float"      # 心率变异性指数

diagnostic_opinion:
  accurate_diagnosis: "string"                # 准确的诊断名称

comparative_study:
  compared_with_past_ecg: "string"            # 与既往心电图对比描述
  change_description: "string"                # 变化描述，如“心律失常发作增多”、“心率变异性降低”等

report_details:
  report_generated_date: "YYYY-MM-DD"         # 报告生成日期
  report_generated_time: "HH:MM"              # 报告生成时间
  cardiologist_name: "string"                 # 心脏病专科医生姓名
  cardiologist_signature: "string"            # 心脏病专科医生签名
  report_number: "string"                     # 报告编号
  remarks: "string"                           # 备注

attachments_and_additional_info:
  image_links:                                # 影像图像链接列表
    - "string"                                # 例如："http://example.com/ecg_image1"
    - "string"                                # 例如："http://example.com/ecg_image2"
  external_reports:                           # 外部相关报告链接列表（如适用）
    - "string"                                # 例如："http://example.com/external_report1"
    - "string"                                # 例如："http://example.com/external_report2"
  additional_documents:                       # 其他补充文件链接列表（如适用）
    - "string"                                # 例如："http://example.com/doc1"
    - "string"                                # 例如："http://example.com/doc2"
  report_notes:                               # 报告附注（如适用）
    - "string"                                # 例如："建议进行心脏超声检查"
    - "string"                                # 例如："推荐进行血液检查"
